version: '3.3'

services:
  db:
    build: db
    image: gtardif/sentences-db

  words:
    build: words
    image: gtardif/sentences-api

  web:
    build: web
    image: gtardif/sentences-web
    ports:
      - "80:80"
    secrets:
      - source: mysecret1
        target: mytarget1
      - mysecret2
    volumes:
      - mydata:/mount/testvolumes

volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: gtashare1      
      storage_account_name: gtastorageaccount1       
      storage_account_key: UZyyUyZJA0LYrPrXqvB+HP+gGWD0K54LNmtfV+xwGQ18JufaAQ7vtUhcJoEcFUUrm40mehLKtvi4n58w0ivDtQ==

secrets:
  mysecret1:
    file: ./my_secret1.txt
  mysecret2:
    file: ./my_secret2.txt
