name: Continuous integration

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        env:
          GO111MODULE: "on"
          GOROOT: ""
        uses: actions-contrib/golangci-lint@v1
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make -f builder.Makefile test

      - name: Build
        run: make -f builder.Makefile cli

      - name: E2E Test
        run: make e2e-local
